title: Wheelchair
description: A prototyping platform for data-centric design with wheelchairs
theme: just-the-docs

url: https://datacentricdesign.github.io/wheelchair/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
